"""Encode the local dev sample (data/dev/raw) into web-ready layers + manifest.

LICENCE: the input under data/dev/raw is derived from the CorrDiff package's
CC BY-NC-ND 4.0 sample dataset. Everything this tool writes stays inside
data/dev/ (gitignored, local-only). Nothing here may be committed or deployed —
the shipped site uses exclusively our own model output. Committed-safe fixture
data comes from `python -m latentsky.make_sample` instead.

Emits, per Architecture.md §5.4/§7/§10 and the dev-sample plan:
  * wind10m-fine            hero-fine    579x566   paired with wind10m-coarse
  * wind10m-coarse          hero-coarse  579x566   (NVIDIA's resample of the 0.25 deg
                                                    input onto the fine grid) paired back
  * wind10m-coarse-native   hero-coarse  40x36     the HONEST native 0.25 deg input grid,
                                                    to be NEAREST-magnified by the viewer
  * mrr-fine                hero-fine    579x566   no coarse pair — the coarse model
                                                    cannot produce reflectivity at all
  * t2m-fine                hero-fine    579x566
  * t2m-coarse              hero-coarse  579x566
All five timesteps each; vmin/vmax GLOBAL from ramps.yaml; identity gate enforced
before the manifest is written; payload table + 12 MB ceiling check at the end.

Usage:
    python -m latentsky.encode_dev --raw data/dev/raw --out data/dev/encoded
"""

from __future__ import annotations

import argparse
import json
import pathlib
import shutil
import sys
import time

import numpy as np

from . import budget, regrid
from .encode import LayerRecord, encode_frame, load_lut, make_layer_record
from .manifest import build_manifest, run_hints, write_manifest
from .ramps import DEFAULT_CONFIG, DEFAULT_LUT_DIR, load_ramps

# The honest native input grid — CorrDiffTaiwan.input_coords() (§3.4.1):
#   lat: linspace(19.25, 28, 36, endpoint=True)   -> 0.25 deg centres
#   lon: linspace(116, 126, 40, endpoint=False)   -> 0.25 deg centres
# As an image of 0.25 deg cells centred on those points:
NATIVE_COARSE_GRID = regrid.TargetGrid(
    west=116.0 - 0.125, south=19.25 - 0.125, east=125.75 + 0.125, north=28.0 + 0.125,
    width=40, height=36,
)

GENERATED_NOTE = (
    "In the finished piece the fine layer is generated by a diffusion model "
    "(CorrDiffTaiwan) — one plausible sample, not observed or resolved truth. "
    "This development sample is CorrDiff training-era CWB/WRF analysis data from 2021 "
    "(including Typhoon Chanthu, 12 September), standing in for model output. "
    "It is not a forecast."
)

# First-class run hints for the dev sample, in the same snake_case shape as
# configs/event_*.yaml so both routes go through manifest.run_hints(). The UI
# previously regex-parsed the storm name out of GENERATED_NOTE and guessed the
# hero frame as "last" — these make both facts data, not heuristics.
# hero_frame 3 is 2021-09-12T00:00:00Z, the Typhoon Chanthu frame (dev_meta.json
# times[3]; the fifth frame, 12Z, is Chanthu weakening — 00Z is the developed one).
DEV_HINTS = {
    "storm_name": "Typhoon Chanthu",
    "hero_frame": 3,
    "place_label": "Taiwan · CWA model domain",
}


def encode_layers(raw_dir: pathlib.Path, out_dir: pathlib.Path,
                  config: pathlib.Path, lut_dir: pathlib.Path,
                  hints: dict = DEV_HINTS) -> None:
    t0 = time.perf_counter()

    npz = np.load(raw_dir / "cwb_sample.npz")
    meta = json.loads((raw_dir / "dev_meta.json").read_text(encoding="utf-8"))
    lat, lon = npz["lat"], npz["lon"]
    times: list[str] = meta["times"]

    specs = load_ramps(config)

    # Regrid mappings: build each KD-tree/index ONCE, apply to every field and frame.
    fine_grid = regrid.target_from_bbox(lat, lon, oversample=1.25)
    print(f"fine target grid: {fine_grid.width}x{fine_grid.height} "
          f"rect [{fine_grid.west:.4f}, {fine_grid.south:.4f}, "
          f"{fine_grid.east:.4f}, {fine_grid.north:.4f}]")
    if (fine_grid.width, fine_grid.height) != (579, 566):
        raise RuntimeError(
            f"expected the §5.4 measured 579x566 target, got "
            f"{fine_grid.width}x{fine_grid.height} — grid rule drifted"
        )
    fine_index = regrid.build_index(lat, lon, fine_grid)
    native_index = regrid.build_index(lat, lon, NATIVE_COARSE_GRID)

    # (layer_id, kind, variable, source npz key, index, label suffix, pair_with)
    plan = [
        ("wind10m-fine", "hero-fine", "wind10m", "fine_wind10m", fine_index,
         " — generated, ~2 km", "wind10m-coarse"),
        ("wind10m-coarse", "hero-coarse", "wind10m", "coarse_wind10m", fine_index,
         " — 0.25° input, resampled", "wind10m-fine"),
        ("wind10m-coarse-native", "hero-coarse", "wind10m", "coarse_wind10m", native_index,
         " — 0.25° model grid, shown at native resolution", None),
        ("mrr-fine", "hero-fine", "mrr", "fine_mrr", fine_index,
         " — generated, ~2 km (no coarse equivalent exists)", None),
        ("t2m-fine", "hero-fine", "t2m", "fine_t2m", fine_index,
         " — generated, ~2 km", None),
        ("t2m-coarse", "hero-coarse", "t2m", "coarse_t2m", fine_index,
         " — 0.25° input, resampled", None),
    ]

    out_dir.mkdir(parents=True, exist_ok=True)

    # Vendor the LUTs the layers use into the output so it is self-contained.
    luts: dict[str, tuple[np.ndarray, str, str]] = {}  # variable -> (lut, sha, rel path)
    (out_dir / "luts").mkdir(exist_ok=True)
    for variable in {p[2] for p in plan}:
        src = lut_dir / specs[variable].lut_filename
        if not src.is_file():
            raise FileNotFoundError(
                f"{src} missing — bake the committed LUTs first: python -m latentsky.ramps"
            )
        rel = f"luts/{specs[variable].lut_filename}"
        shutil.copyfile(src, out_dir / rel)
        lut, sha = load_lut(out_dir / rel)
        luts[variable] = (lut, sha, rel)

    records: list[LayerRecord] = []
    layer_bytes: dict[str, int] = {}
    for layer_id, kind, variable, key, index, suffix, pair in plan:
        spec = specs[variable]
        lut, lut_sha, lut_rel = luts[variable]
        stack = npz[key]
        if stack.shape[0] != len(times):
            raise RuntimeError(f"{key}: {stack.shape[0]} frames but {len(times)} times")
        frames: list[str] = []
        total = 0
        for i in range(stack.shape[0]):
            rel = f"layers/{layer_id}/{i:03d}.webp"
            field = index.apply(stack[i])
            total += encode_frame(field, lut, spec.vmin, spec.vmax, out_dir / rel,
                                  valid=index.valid)
            frames.append(rel)
        layer_bytes[layer_id] = total
        records.append(make_layer_record(
            layer_id=layer_id, kind=kind, spec=spec, lut_sha256=lut_sha,
            lut_rel_path=lut_rel, rect=index.grid.rect, size=index.grid.size,
            frames=frames, label_suffix=suffix, pair_with=pair,
        ))
        w, h = index.grid.size
        print(f"  {layer_id:22s} {kind:11s} {w:4d}x{h:<4d} "
              f"{len(frames)} frames  {total:>9,} B  ({total / len(frames):,.0f} B/frame)")

    run = {
        "id": "dev-cwb-sample",
        "kind": "dev-sample",
        "model": {
            "prognostic": "ERA5 0.25° analysis (coarse input, resampled onto the CWB grid "
                          "by the package authors)",
            "downscaling": "CorrDiffTaiwan training-era CWB/WRF ~2 km analysis "
                           "(dev stand-in for diffusion output)",
        },
        "generatedNote": GENERATED_NOTE,
        **run_hints(hints),
    }
    manifest = build_manifest(run, times, records, specs)
    manifest_path = write_manifest(manifest, out_dir)
    print(f"\nmanifest validated against schema and written: {manifest_path}")

    print(f"encode wall time: {time.perf_counter() - t0:.1f} s")
    _, within = budget.report(out_dir)
    if not within:
        raise SystemExit(1)


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--raw", type=pathlib.Path, required=True)
    ap.add_argument("--out", type=pathlib.Path, required=True)
    ap.add_argument("--config", type=pathlib.Path, default=DEFAULT_CONFIG)
    ap.add_argument("--luts", type=pathlib.Path, default=DEFAULT_LUT_DIR)
    ap.add_argument("--event-config", type=pathlib.Path, default=None,
                    help="Event yaml whose storm_name/hero_frame/place_label override "
                         "the dev-sample hints (the path a real run's encode takes)")
    args = ap.parse_args(argv)
    hints = DEV_HINTS
    if args.event_config is not None:
        import yaml

        hints = yaml.safe_load(args.event_config.read_text(encoding="utf-8"))
    encode_layers(args.raw, args.out, args.config, args.luts, hints=hints)


if __name__ == "__main__":
    main()
