"""Encode a REAL forecast run (the Zarr pair from forecast.py) into web layers.

This is the tool that turns rented-GPU output into the thing the site shows. It
is the publishable sibling of encode_dev: same six layer ids, same LUTs, same
grid rule — so the viewer renders a real run with no code change at all — but the
input is our own model output rather than the CC BY-NC-ND dev sample.

LICENCE: everything here is publishable. The fine field is CorrDiffTaiwan output
(Apache-2.0 checkpoint) driven by SFNO (Apache-2.0) from ERA5/ARCO initial
conditions (CC-BY, Copernicus). Nothing from the CorrDiff sample dataset is read,
and the grid we publish on is one we define (§3.10), so the package's XLAT/XLONG
arrays are never redistributed either.

forecast.py writes TWO stores, because zarr keys coordinate arrays by name and the
two grids cannot share one:
    <out>.zarr        coarse global   u10m v10m t2m tcwv msl   [1, 21, 721, 1440]
    <out>_hero.zarr   CorrDiff hero   hero_{mrr,t2m,u10m,v10m} [1, 12, 4, 448, 448]
                                      with 2-D curvilinear lat/lon

The coarse side of the reveal is the SAME 0.25° field CorrDiff was conditioned on,
subset to its input box (lat 19.25..28, lon 116..125.75 — exactly 36x40 cells),
which is what makes the wipe an honest before/after rather than two unrelated
pictures.

Usage — pass --event-id so run.id matches the catalogue entry (the configs carry
no id of their own, and the filename stem makes an ugly run identity):

    python -m latentsky.encode_forecast \
        --zarr data/zarr/gaemi_2024.zarr \
        --event-config pipeline/configs/event_gaemi_2024.yaml \
        --out data/web/taiwan --event-id taiwan-gaemi-2024

    python -m latentsky.encode_forecast \
        --zarr data/zarr/doksuri_2023.zarr \
        --event-config pipeline/configs/event_doksuri_2023.yaml \
        --out data/web/taiwan-doksuri --event-id taiwan-doksuri-2023

then rebuild the index over the full registry:

    python -m latentsky.catalogue --root data/web
"""

from __future__ import annotations

import argparse
import pathlib
import shutil
import time

import numpy as np
import yaml

from . import basemap as basemap_mod, budget, catalogue as catalogue_mod, regrid
from .encode import LayerRecord, encode_frame, load_lut, make_layer_record
from .encode_global import BASEMAP_REL, GLOBAL_GRID
from .manifest import build_manifest, run_hints, write_manifest
from .ramps import DEFAULT_CONFIG, DEFAULT_LUT_DIR, load_ramps

# CorrDiffTaiwan.input_coords() — the honest native input grid (§3.4.1):
#   lat: linspace(19.25, 28, 36, endpoint=True)
#   lon: linspace(116, 126, 40, endpoint=False)
# As an image of 0.25° cells centred on those points:
NATIVE_LAT = np.linspace(19.25, 28.0, 36)
NATIVE_LON = np.linspace(116.0, 126.0, 40, endpoint=False)
NATIVE_COARSE_GRID = regrid.TargetGrid(
    west=116.0 - 0.125, south=19.25 - 0.125, east=125.75 + 0.125, north=28.0 + 0.125,
    width=40, height=36,
)

# The sample the shipped layers use. The honesty-panel step carries four; every
# other step carries one, and mixing them across frames would make the animation
# jump between draws of the same distribution.
HERO_SAMPLE = 0

GENERATED_NOTE = (
    "The fine layer is generated by a diffusion model (CorrDiffTaiwan) conditioned "
    "on a 0.25° SFNO forecast — one plausible sample, not observed or resolved "
    "truth. Both models are run here from ERA5 reanalysis initial conditions, so "
    "this is a hindcast of a past event: the outcome is already known, and the "
    "point is what the models produce, not a prediction."
)


class EncodeForecastError(RuntimeError):
    """The forecast could not be encoded. The build must stop."""


def open_stores(coarse_path: pathlib.Path) -> tuple:
    """Open the coarse store and its _hero sibling, which forecast.py writes together."""
    import zarr

    coarse_path = pathlib.Path(coarse_path)
    hero_path = coarse_path.with_name(coarse_path.stem + "_hero" + coarse_path.suffix)
    for path in (coarse_path, hero_path):
        if not path.is_dir():
            raise EncodeForecastError(
                f"{path} missing — encode_forecast needs BOTH stores forecast.py writes "
                f"({coarse_path.name} and {hero_path.name}); untar the run archive whole"
            )
    return zarr.open(str(coarse_path), mode="r"), zarr.open(str(hero_path), mode="r")


def frame_times(coarse, hero) -> list[str]:
    """ISO instants for the hero window: init + each hero lead_time."""
    init = np.asarray(coarse["time"])[0]
    leads = np.asarray(hero["lead_time"])
    return [
        np.datetime_as_string(init + lead.astype("timedelta64[ns]"), unit="s") + "Z"
        for lead in leads
    ]


def taiwan_subset(coarse) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Row/col selectors for CorrDiff's input box, gated to the exact 36x40 cells.

    The gate matters: a silently-wrong box would still produce a plausible-looking
    picture, just one that is not the field the diffusion model actually saw.
    """
    lat = np.asarray(coarse["lat"])
    lon = np.asarray(coarse["lon"])
    rows = np.where((lat >= NATIVE_LAT.min() - 1e-6) & (lat <= NATIVE_LAT.max() + 1e-6))[0]
    cols = np.where((lon >= NATIVE_LON.min() - 1e-6) & (lon <= NATIVE_LON.max() + 1e-6))[0]
    if (len(rows), len(cols)) != (36, 40):
        raise EncodeForecastError(
            f"CorrDiff input box selected {len(rows)}x{len(cols)} cells, expected 36x40 — "
            "the coarse grid is not the 0.25° global grid this assumes"
        )
    return rows, cols, lat[rows]


def encode_layers(
    zarr_path: pathlib.Path,
    out_dir: pathlib.Path,
    event_config: pathlib.Path,
    config: pathlib.Path = DEFAULT_CONFIG,
    lut_dir: pathlib.Path = DEFAULT_LUT_DIR,
    catalogue_config: pathlib.Path = catalogue_mod.DEFAULT_CONFIG,
    tiles_dir: pathlib.Path = basemap_mod.DEFAULT_TILES,
    coastline_path: pathlib.Path = basemap_mod.DEFAULT_COASTLINE,
    event_id: str | None = None,
) -> None:
    t0 = time.perf_counter()
    out_dir = pathlib.Path(out_dir)
    cfg = yaml.safe_load(pathlib.Path(event_config).read_text(encoding="utf-8"))

    coarse, hero = open_stores(zarr_path)
    times = frame_times(coarse, hero)
    nframes = len(times)
    specs = load_ramps(config)

    # ── Grids ──────────────────────────────────────────────────────────────
    hero_lat = np.asarray(hero["lat"])
    hero_lon = np.asarray(hero["lon"])
    fine_grid = regrid.target_from_bbox(hero_lat, hero_lon)
    print(
        f"fine target grid: {fine_grid.width}x{fine_grid.height} "
        f"rect [{fine_grid.west:.4f}, {fine_grid.south:.4f}, "
        f"{fine_grid.east:.4f}, {fine_grid.north:.4f}]"
    )
    fine_index = regrid.build_index(hero_lat, hero_lon, fine_grid)

    rows, cols, sub_lat = taiwan_subset(coarse)
    coarse_lat2d, coarse_lon2d = np.meshgrid(sub_lat, NATIVE_LON, indexing="ij")
    # The 0.25° input rendered two ways: resampled onto the fine grid (so the wipe
    # compares identical geometry and the blockiness is the honest difference), and
    # at its own native cell size (so the input is never implied to be finer).
    coarse_on_fine = regrid.build_index(coarse_lat2d, coarse_lon2d, fine_grid)
    coarse_native = regrid.build_index(coarse_lat2d, coarse_lon2d, NATIVE_COARSE_GRID)

    # ── Field readers, each returning (frame_index) -> 2-D source field ─────
    def hero_field(name: str):
        arr = hero[f"hero_{name}"]

        def read(i: int) -> np.ndarray:
            return np.asarray(arr[0, i, HERO_SAMPLE])

        return read

    def hero_wind():
        u, v = hero["hero_u10m"], hero["hero_v10m"]

        def read(i: int) -> np.ndarray:
            return np.hypot(
                np.asarray(u[0, i, HERO_SAMPLE]), np.asarray(v[0, i, HERO_SAMPLE])
            )

        return read

    def coarse_field(name: str):
        arr = coarse[name]

        def read(i: int) -> np.ndarray:
            return np.asarray(arr[0, i])[np.ix_(rows, cols)]

        return read

    def coarse_wind():
        u, v = coarse["u10m"], coarse["v10m"]

        def read(i: int) -> np.ndarray:
            return np.hypot(
                np.asarray(u[0, i])[np.ix_(rows, cols)],
                np.asarray(v[0, i])[np.ix_(rows, cols)],
            )

        return read

    # (layer_id, kind, variable, reader, index, label suffix, pair_with, native_km)
    plan = [
        ("wind10m-fine", "hero-fine", "wind10m", hero_wind(), fine_index,
         " — generated, ~2 km", "wind10m-coarse", 2.0684),
        ("wind10m-coarse", "hero-coarse", "wind10m", coarse_wind(), coarse_on_fine,
         " — 0.25° model input, resampled", "wind10m-fine", 25.0),
        ("wind10m-coarse-native", "hero-coarse", "wind10m", coarse_wind(), coarse_native,
         " — 0.25° model grid, shown at native resolution", None, 25.0),
        ("mrr-fine", "hero-fine", "mrr", hero_field("mrr"), fine_index,
         " — generated, ~2 km (no coarse equivalent exists)", None, 2.0684),
        ("t2m-fine", "hero-fine", "t2m", hero_field("t2m"), fine_index,
         " — generated, ~2 km", None, 2.0684),
        ("t2m-coarse", "hero-coarse", "t2m", coarse_field("t2m"), coarse_on_fine,
         " — 0.25° model input, resampled", None, 25.0),
    ]

    prepare_out_dir(out_dir)

    # Vendor the LUTs so the event tree is self-contained and byte-identical to
    # the global tree's copies (colour identity is checked by the encode tests).
    luts: dict[str, tuple[np.ndarray, str, str]] = {}
    (out_dir / "luts").mkdir()
    for variable in sorted({p[2] for p in plan}):
        src = pathlib.Path(lut_dir) / specs[variable].lut_filename
        if not src.is_file():
            raise EncodeForecastError(
                f"{src} missing — bake the committed LUTs first: python -m latentsky.ramps"
            )
        rel = f"luts/{specs[variable].lut_filename}"
        shutil.copyfile(src, out_dir / rel)
        lut, sha = load_lut(out_dir / rel)
        luts[variable] = (lut, sha, rel)

    records: list[LayerRecord] = []
    for layer_id, kind, variable, read, index, suffix, pair, native_km in plan:
        spec = specs[variable]
        lut, lut_sha, lut_rel = luts[variable]
        frames: list[str] = []
        total = 0
        for i in range(nframes):
            rel = f"layers/{layer_id}/{i:03d}.webp"
            field = index.apply(read(i))
            total += encode_frame(
                field, lut, spec.vmin, spec.vmax, out_dir / rel, valid=index.valid
            )
            frames.append(rel)
        records.append(
            make_layer_record(
                layer_id=layer_id, kind=kind, spec=spec, lut_sha256=lut_sha,
                lut_rel_path=lut_rel, rect=index.grid.rect, size=index.grid.size,
                frames=frames, label_suffix=suffix, pair_with=pair,
                native_km=native_km,
            )
        )
        w, h = index.grid.size
        print(f"  {layer_id:22s} {kind:11s} {w:4d}x{h:<4d} "
              f"{len(frames)} frames  {total:>9,} B  ({total / len(frames):,.0f} B/frame)")

    run = {
        "id": event_id or cfg.get("id") or pathlib.Path(event_config).stem,
        "kind": "forecast",
        "model": {
            "prognostic": "NVIDIA SFNO 73-channel, 0.25° global (Apache-2.0 checkpoint), "
                          "initialised from ERA5/ARCO",
            "downscaling": "NVIDIA CorrDiffTaiwan diffusion downscaler, ~2 km "
                           "(Apache-2.0 checkpoint)",
        },
        "generatedNote": GENERATED_NOTE,
        **run_hints(cfg),
    }
    # Bake the dark basemap into THIS event tree. Not optional and not shared by
    # reference: ?event=taiwan-gaemi-2024 opens this manifest first, with no other
    # event ever loaded, so an event that does not carry base imagery draws its
    # hero patch on a black globe. basemap.bake is deterministic, so these bytes
    # are identical to the global tree's copy (106 KB, Natural Earth II, public
    # domain — shippable).
    size = basemap_mod.bake(tiles_dir, out_dir / BASEMAP_REL, coastline_path=coastline_path)
    print(f"  basemap baked: {BASEMAP_REL}  {size:,} B")

    manifest = build_manifest(
        run, times, records, specs,
        basemap={"global": BASEMAP_REL, "globalRect": GLOBAL_GRID.rect},
    )
    manifest_path = write_manifest(manifest, out_dir)
    print(f"\nmanifest validated against schema and written: {manifest_path}")

    print(f"encode wall time: {time.perf_counter() - t0:.1f} s")
    budget.report(out_dir)


def prepare_out_dir(out_dir: pathlib.Path) -> None:
    """Replace what this tool owns; refuse anything it does not.

    Same contract as encode_public.prepare_out_dir, scoped to one event subtree:
    a stray file would make the tree hash lie about what a re-run produces.
    """
    managed = ("layers", "luts", "basemap", "manifest.json")
    out_dir = pathlib.Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    for name in managed:
        path = out_dir / name
        if path.is_dir():
            shutil.rmtree(path)
        elif path.exists():
            path.unlink()
    strangers = sorted(p.name for p in out_dir.iterdir())
    if strangers:
        raise EncodeForecastError(
            f"{out_dir} contains entries this tool does not manage: {strangers} — "
            "delete them (or move them out) so the emitted tree means what it claims."
        )


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--zarr", type=pathlib.Path, required=True,
                    help="the COARSE store; the _hero sibling is found beside it")
    ap.add_argument("--out", type=pathlib.Path, required=True)
    ap.add_argument("--event-config", type=pathlib.Path, required=True)
    ap.add_argument("--config", type=pathlib.Path, default=DEFAULT_CONFIG)
    ap.add_argument("--luts", type=pathlib.Path, default=DEFAULT_LUT_DIR)
    ap.add_argument("--event-id", default=None,
                    help="run.id for the manifest; defaults to the config's id/stem")
    args = ap.parse_args(argv)
    encode_layers(
        args.zarr, args.out, args.event_config,
        config=args.config, lut_dir=args.luts, event_id=args.event_id,
    )


if __name__ == "__main__":
    main()
