"""Generate data/sample/ — a tiny SYNTHETIC, licence-clean fixture dataset.

Two frames of a procedural swirl (a Rankine-style vortex plus deterministic
fine-scale texture) on a synthetic rotated curvilinear grid, run through the
SAME pipeline as real data — regrid.build_index -> encode_frame -> manifest —
so CI and the web app exercise the true code path with data that is safe to
commit. Everything here is generated by this script from constants: no model
output, no observations, nothing derived from any licensed dataset.

The "coarse" layer is the fine field Gaussian-smoothed, mimicking the
resolution relationship of the real pair, and both layers share the GLOBAL
wind10m ramp — so the fixture also exercises the identity gate and the wipe.

Deterministic: fixed seed, fixed parameters; re-running must be byte-identical.

Usage:
    python -m latentsky.make_sample --out data/sample
"""

from __future__ import annotations

import argparse
import pathlib
import shutil

import numpy as np
from scipy.ndimage import gaussian_filter

from . import budget, regrid
from .encode import encode_frame, load_lut, make_layer_record
from .manifest import build_manifest, write_manifest
from .ramps import DEFAULT_CONFIG, DEFAULT_LUT_DIR, load_ramps

FRAME_TIMES = ["2000-01-01T00:00:00Z", "2000-01-01T06:00:00Z"]  # deliberately unreal
SIZE = 64          # target pixels per side
SRC_N = 96         # synthetic curvilinear source grid per side
GENERATED_NOTE = (
    "Synthetic fixture data — a procedural swirl field produced by "
    "latentsky.make_sample so that CI and the web app have licence-clean data. "
    "Not model output, not observations, and not a forecast."
)


def _synthetic_grid() -> tuple[np.ndarray, np.ndarray]:
    """A rotated curvilinear grid over a fictional 2-degree box near 23.5N 121E,
    with the same rotated character as the real WRF grid."""
    j, i = np.meshgrid(
        np.arange(SRC_N) - (SRC_N - 1) / 2, np.arange(SRC_N) - (SRC_N - 1) / 2, indexing="xy"
    )
    theta = np.radians(8.0)
    step = 0.022
    x = (j * np.cos(theta) - i * np.sin(theta)) * step
    y = (j * np.sin(theta) + i * np.cos(theta)) * step
    lat = 23.5 + y
    lon = 121.0 + x / np.cos(np.radians(23.5))
    return lat, lon


def _swirl(lat: np.ndarray, lon: np.ndarray, frame: int) -> np.ndarray:
    """Wind-speed-like field, m/s: a translating vortex + texture, range ~0..50."""
    centre_lat = 23.35 + 0.25 * frame
    centre_lon = 121.15 - 0.20 * frame
    dy = lat - centre_lat
    dx = (lon - centre_lon) * np.cos(np.radians(23.5))
    r = np.hypot(dx, dy)
    rc = 0.18                                     # radius of maximum wind, degrees
    speed = np.where(r < rc, 46.0 * r / rc, 46.0 * (rc / np.maximum(r, 1e-9)) ** 0.8)
    az = np.arctan2(dy, dx)
    spiral = 4.0 * np.sin(3.0 * az + 14.0 * r - 1.5 * frame)  # rain-band-ish spiral arms
    rng = np.random.default_rng(1234 + frame)                  # deterministic per frame
    texture = gaussian_filter(rng.standard_normal(lat.shape), sigma=1.5) * 2.5
    calm_eye = np.clip(r / 0.05, 0.0, 1.0)                     # near-calm eye
    return np.clip((speed + spiral + texture) * calm_eye + 1.5, 0.0, 55.0)


def make_sample(out_dir: pathlib.Path, config: pathlib.Path, lut_dir: pathlib.Path) -> None:
    specs = load_ramps(config)
    spec = specs["wind10m"]

    lat, lon = _synthetic_grid()
    grid = regrid.TargetGrid(
        west=float(lon.min()), south=float(lat.min()),
        east=float(lon.max()), north=float(lat.max()),
        width=SIZE, height=SIZE,
    )
    index = regrid.build_index(lat, lon, grid)

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "luts").mkdir(exist_ok=True)
    lut_src = lut_dir / spec.lut_filename
    if not lut_src.is_file():
        raise FileNotFoundError(f"{lut_src} missing — run: python -m latentsky.ramps")
    lut_rel = f"luts/{spec.lut_filename}"
    shutil.copyfile(lut_src, out_dir / lut_rel)
    lut, lut_sha = load_lut(out_dir / lut_rel)

    records = []
    for layer_id, kind, sigma, suffix, pair in [
        ("wind10m-fine", "hero-fine", 0.0, " — synthetic fine", "wind10m-coarse"),
        ("wind10m-coarse", "hero-coarse", 6.0, " — synthetic coarse", "wind10m-fine"),
    ]:
        frames = []
        total = 0
        for i in range(len(FRAME_TIMES)):
            field = _swirl(lat, lon, i)
            if sigma > 0:
                field = gaussian_filter(field, sigma=sigma)  # the "coarse" stand-in
            rel = f"layers/{layer_id}/{i:03d}.webp"
            total += encode_frame(
                index.apply(field), lut, spec.vmin, spec.vmax, out_dir / rel,
                valid=index.valid,
            )
            frames.append(rel)
        records.append(make_layer_record(
            layer_id=layer_id, kind=kind, spec=spec, lut_sha256=lut_sha,
            lut_rel_path=lut_rel, rect=grid.rect, size=grid.size,
            frames=frames, label_suffix=suffix, pair_with=pair,
        ))
        print(f"  {layer_id:16s} {kind:11s} {SIZE}x{SIZE}  "
              f"{len(frames)} frames  {total:>6,} B")

    run = {
        "id": "synthetic-swirl",
        "kind": "dev-sample",
        "model": {
            "prognostic": "synthetic — procedural swirl (latentsky.make_sample)",
            "downscaling": "synthetic — Gaussian-smoothed swirl (fixture)",
        },
        "generatedNote": GENERATED_NOTE,
    }
    manifest = build_manifest(run, FRAME_TIMES, records, specs)
    path = write_manifest(manifest, out_dir)
    print(f"\nmanifest validated against schema and written: {path}")

    total, within = budget.report(out_dir, ceiling_mb=0.5)  # §11: committed sample < 500 KB
    if not within:
        raise SystemExit(1)


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", type=pathlib.Path, required=True)
    ap.add_argument("--config", type=pathlib.Path, default=DEFAULT_CONFIG)
    ap.add_argument("--luts", type=pathlib.Path, default=DEFAULT_LUT_DIR)
    args = ap.parse_args(argv)
    make_sample(args.out, args.config, args.luts)


if __name__ == "__main__":
    main()
